<style>
    #privacy_container {
        /* margin-top: 50px; */
        /* border-top: 1px solid gainsboro; */
        padding: 15px 20px;

    }

    #privacy_container h3 {
        text-decoration: underline overline;
        text-underline-offset: 7px;
    }
</style>

<div id="privacy_container">
    <p style='margin-top:0in;margin-right:0in;margin-bottom:3.0pt;margin-left:0in;line-height:115%;font-size:35px;font-family:"Arial",sans-serif;'>Privacy Policy for Techsup Flex</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Sanotize Research and development Corp. built the&nbsp;<span style="font-size:13px;line-height:115%;">SaNOtize Registry</span> as a Free app. This SERVICE is provided by Sanotize Research and development Corp. at no cost and is intended for use as is.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>If you choose to use our Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Herdiary unless otherwise defined in this Privacy Policy.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Information Collection and Use</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>For a better experience, while using our Service, we may require you to provide us with certain personally identifiable information, including but not limited to Name, Age, Contact Number, Email Id, Photos, Occupation, Relationship Status, Family Details Details. The information that we request will be retained by us and used as described in this privacy policy.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Log Data</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>We want to inform you that whenever you use our Service, in a case of an error in the app we collect data and information (through third-party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (&ldquo;IP&rdquo;) address, device name, operating system version, the configuration of the app when utilizing our Service, the time and date of your use of the Service, and other statistics.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Cookies</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device&rsquo;s internal memory.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>This Service does not use these &ldquo;cookies&rdquo; explicitly. However, the app may use third-party code and libraries that use &ldquo;cookies&rdquo; to collect information and improve their services. You have the option to either accept or refuse these</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Service Providers</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>We may employ third-party companies and individuals due to the following reasons:</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&bull; To facilitate our Service</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&bull; To provide the Service on our behalf</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&bull; To perform Service-related services; or</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&bull; To assist us in analyzing how our Service is used.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Security</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Links to Other Sites</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>EU Members&rsquo; Rights (GDPR Compliant)</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>If you are habitually located in the European Union, you have the right to access, rectify, download or erase your information, as well as the right to restrict and object to certain processing of your information. While some of these rights apply generally, certain rights apply only in certain limited circumstances.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>We describe these rights below:</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong>Access and Porting:&nbsp;</strong>You can access your information at any time.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong>Rectify, Restrict, Limit, Delete:</strong> You can also rectify, restrict, limit or delete much of your information by contacting us.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong>Object:</strong> Where we process your information based on our legitimate interests explained above, or in the public interest, you can object to this processing in certain circumstances. In such cases, we will cease processing your information unless we have compelling legitimate grounds to continue processing or where it is needed for legal reasons.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong>Revoke consent:</strong> Where you have previously provided your consent, such as to permit us to process health-related data about you, you have the right to withdraw your consent to the processing of your information at any time. For example, you can withdraw your consent by updating your settings. In certain cases, we may continue to process your information after you have withdrawn consent if we have a legal basis to do so or if your withdrawal of consent was limited to certain processing activities.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong>Complain:</strong> Should you wish to raise a concern about our use of your information (and without prejudice to any other rights you may have), you have the right to do so with your local supervisory authority.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Additionally, if you are a European resident, we note that we are processing your information in order to fulfill contracts we might have with you or otherwise to pursue our legitimate business interests listed above. Additionally, please note that your information will be transferred outside of Europe.</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Children&rsquo;s Privacy</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do the necessary actions.</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Editing And Deleting Information</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>If you believe that any information we are holding on you is incorrect or incomplete, please write to or email us as soon as possible. We will promptly correct any information found to be incorrect. You can change, modify, rectify and delete your Information at any time, please contact us through the contact information.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>To opt out of email, follow the instructions included in the email. Your request should be processed within 48 hours.</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Changes to This Privacy Policy</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Terms &amp; Conditions</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>By downloading or using the app, these terms will automatically apply to you &ndash; you should make sure therefore that you read them carefully before using the app. You&rsquo;re not allowed to copy or modify the app, any part of the app, or our trademarks in any way. You&rsquo;re not allowed to attempt to extract the source code of the app, and you also shouldn&rsquo;t try to translate the app into other languages or make derivative versions. The app itself, and all the trademarks, copyright, database rights, and other intellectual property rights related to it, still belong to Sanotize Research and Development Corp.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Sanotize Research and Development Corp. is committed to ensuring that the app is as useful and efficient as possible. For that reason, we reserve the right to make changes to the app or to charge for its services, at any time and for any reason. We will never charge you for the app or its services without making it very clear to you exactly what you&rsquo;re paying for.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>The Hereditary app stores and processes personal data that you have provided to us, in order to provide our Service. It&rsquo;s your responsibility to keep your phone and access to the app secure. We, therefore, recommend that you do not jailbreak or root your phone, which is the process of removing software restrictions and limitations imposed by the official operating system of your device. It could make your phone vulnerable to malware/viruses/malicious programs, compromise your phone&rsquo;s security features and it could mean that the Herdiary app won&rsquo;t work properly or at all.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>You should be aware that there are certain things that Sanotize Research and development Corp. will not take responsibility for. Certain functions of the app will require the app to have an active internet connection. The connection can be Wi-Fi or provided by your mobile network provider, but Sanotize Research and development Corp. cannot take responsibility for the app not working at full functionality if you don&rsquo;t have access to Wi-Fi, and you don&rsquo;t have any of your data allowance left.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>If you&rsquo;re using the app outside of an area with Wi-Fi, you should remember that the terms of the agreement with your mobile network provider will still apply. As a result, you may be charged by your mobile provider for the cost of data for the duration of the connection while accessing the app, or other third-party charges. In using the app, you&rsquo;re accepting responsibility for any such charges, including roaming data charges if you use the app outside of your home territory (i.e. region or country) without turning off data roaming. If you are not the bill payer for the device on which you&rsquo;re using the app, please be aware that we assume that you have received permission from the bill payer for using the app.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>Along the same lines, Sanotize Research and Development Corp. cannot always take responsibility for the way you use the app i.e. You need to make sure that your device stays charged &ndash; if it runs out of battery and you can&rsquo;t turn it on to avail the Service, Sanotize Research and development Corp. cannot accept responsibility.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>With respect to Sanotize Research and development Corp.&rsquo;s responsibility for your use of the app, when you&rsquo;re using the app, it&rsquo;s important to bear in mind that although we endeavor to ensure that it is updated and correct at all times, we do rely on third parties to provide information to us so that we can make it available to you. Sanotize Research and development Corp. accepts no liability for any loss, direct or indirect, you experience as a result of relying wholly on this functionality of the app.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>At some point, we may wish to update the app. The app is currently available on Android &amp; iOS &ndash; the requirements for both systems (and for any additional systems we decide to extend the availability of the app to) may change, and you&rsquo;ll need to download the updates if you want to keep using the app. Sanotize Research and development Corp. does not promise that it will always update the app so that it is relevant to you and/or works with the Android &amp; iOS versions that you have installed on your device. However, you promise to always accept updates to the application when offered to you, we may also wish to stop providing the app, and may terminate use of it at any time without giving notice of termination to you. Unless we tell you otherwise, upon any termination, (a) the rights and licenses granted to you in these terms will end; (b) you must stop using the app, and (if needed) delete it from your device.</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <h1 style='margin-top:20.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:27px;font-family:"Arial",sans-serif;font-weight:normal;'>Changes to This Terms and Conditions</h1>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
    <p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>We may update our Terms and Conditions from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Terms and Conditions on this page. These changes are effective immediately after they are posted on this page.</p>
</div>