<style>
    #privacy_container {
        /* margin-top: 50px; */
        /* border-top: 1px solid gainsboro; */
        padding: 15px 20px;

    }

    #privacy_container h3 {
        text-decoration: underline overline;
        text-underline-offset: 7px;
    }
</style>

<div id="privacy_container">
    <p dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;line-height:20.8pt;'><span style='font-size:15px;font-family:"GE SS Text Light Light",serif;background:white;'>&nbsp;</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:center;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>سياسة الخصوصية لتطبيق تكسب&nbsp;</span><span dir="RTL" style='font-family:"Arial",sans-serif;background:white;'>فليكس</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>البند الأول</span><span style='font-family:"GE SS Two Medium Medium",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>مقدمة</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>إيمانًا بأهمية البيانات وسريتها، وحرصًا من إدارة شركة تكسب المساندة للتسويق على تقديم أفضل مستويات الخدمة، مع الالتزام بالمحافظة على سرية وخصوصية بيانات المستخدم والبيانات المدخلة، فإن إدارة الشركة تلتزم بالمحافظة على سرية وخصوصية معلومات المستخدم والمواد المدخلة من قبلهم كأساس لسياسة الخصوصية، ولن تقوم إدارة الشركة بالإفصاح عن تلك المعلومات إلا وفقًا للضوابط المحددة والمنصوص عليها في البند الرابع&nbsp;</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>(</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>الاستخدام والإفصاح</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>)</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>البند الثاني</span><span style='font-family:"GE SS Two Medium Medium",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>معلومات المستخدم</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>يقصد ببيانات ومعلومات المستخدم كل وأيّ مما يلي</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>:</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>أ</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>البيانات الشخصية المستخدمة في التسجيل</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-family:"GE SS Text Light Light",serif;background:white;'>ب</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>بيانات الموقع الجغرافي للمستخدم وتحركاته</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-family:"GE SS Text Light Light",serif;background:white;'>ج</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>معلومات بيانات الاتصال والتحديثات المتعلقة بالاستخدام</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>د</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>المعلومات الأخرى المدخلة من المستخدم مثل تقارير الحضور و الإنصراف ، التقاطات الشاشة عند استخدم النظام من أجهزة الكمبيوتر ، الملفات و المرفقات وإجابات الاستبيانات ان وجدت</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>البند الثالث</span><span style='font-family:"GE SS Two Medium Medium",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>جمع المعلومات وتخزينها</span></p>
    <p style='margin-top:1.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>أ</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>جمع المعلومات</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>:</span></p>
    <p style='margin-top:1.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>معلومات الاتصال</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>إن التطبيق يقوم بجمع بعض بيانات الجهاز التي تساعد على تحسين التجربة، مثل لغة الجهاز ونوع النظام</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>.&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>كما يقوم التطبيق&nbsp;</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>&nbsp;</span></p>
    <p style='margin-top:1.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>&nbsp;</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>1</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>تخزين معلومات الدخول و الخروج و المهام المدخلة من قبل صاحب العمل لتحقيق أغراض التعاقد المطلوبة من وزارة الموارد البشرية و الشؤون الاجتماعية</span></p>
    <p style='margin-top:1.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>&nbsp;</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>2</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>المعلومات المدخلة</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>يتم&nbsp;</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>حفظ المعلومات المدخلة من المستخدم مثل أسم المستخدم والمعلومات المطلوبة لإثبات العمل</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.&nbsp;</span></p>
    <p style='margin-top:1.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-family:"GE SS Text Light Light",serif;background:white;'>ب</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>تخزين المعلومات</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>:</span></p>
    <p style='margin-top:1.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>يتم تخزين المعلومات الخاصة بالمستخدم في الخوادم التي تحددها إدارة الشركة داخل المملكة العربية السعودية، وتحرص إدارة الشركة على أن تكون هذه الخوادم محمية من الاختراق والدخول غير المصرح وفق المعايير المتبعة، وتتعهد إدارة الشركة بحذفها من تلك الخوادم بعد سنة من إنتهاء العلاقة التعاقدية</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>&nbsp;البند الرابع</span><span style='font-family:"GE SS Two Medium Medium",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>الاستخدام والإفصاح</span></p>
    <p dir="RTL" style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-family:"GE SS Text Light Light",serif;background:white;'>أ</span><span style='font-family:"Arial Unicode MS",sans-serif;background:white;'>-&nbsp;</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>حماية المعلومات الشخصية</span><span style='font-family:"Arial Unicode MS",sans-serif;background:white;'>&nbsp;</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>لن تكون معلومات المستخدم متاحة إلا لموظفي الشركة الذين يحتاجون إلى الاطلاع عليها، ولن تكون تلك المعلومات متاحة لاطلاع الجمهور دون موافقتكم &nbsp;ولن يتم تبادل، أو تداول، أي من تلك المعلومات أو بيعها لأي طرف آخر من غير موافقة المستخدم المسبقة، ولن يُسمح بالوصول إلى المعلومات إلا لمن يتولى تقديم خدمات بوابة الوزارة المتسقة مع تعاملات المستخدم</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>مع الموقع ، ولا يدخل في مفهوم&nbsp;</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>&quot;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>المعلومات الشخصية</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>&quot;&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>في هذا السياق تعليقاتك ومشاركاتك الإلكترونية التي ترفعها على النظام او الموقع &nbsp;لغرض النشر أو للاستخدام التفاعلي للخدمات</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p dir="RTL" style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-family:"GE SS Text Light Light",serif;background:white;'>ب</span><span dir="LTR" style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>ينحصر حق الاطلاع على معلومات المستخدمين للعاملين المخولين بذلك في إدارة الشركة وللأغراض والاستخدامات التي تحددها السياسات المعتمدة لدى إدارة الشركة بالإضافة لحسابات المدراء المقدمة من الشركة المتعاقدة</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>البند الخامس</span><span style='font-family:"GE SS Two Medium Medium",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>الروابط الخارجية</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>قد يقدم التطبيق روابط لأطراف أخرى، والتطبيق غير مسؤول عن كيفية جمع الأطراف الأخرى أو استخدامها لمعلومات التعريف الشخصية عن المستخدم، ويتحمل المستخدم المسؤولية الكاملة عن بياناته</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>البند السادس</span><span style='font-family:"GE SS Two Medium Medium",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>مسؤولية المستخدم تجاه حماية الخصوصية</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>بهدف حماية معلومات المستخدم فإننا ننصح بما يلي</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>:</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>أ</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>الاتصال الفوري بالدعم الفني للنظام عندما يعتقد المستخدم بأن شخصًا آخر استطاع الحصول على معلومات الدخول إلى حسابه في التطبيق أو أي معلومة سرية أخرى</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-family:"GE SS Text Light Light",serif;background:white;'>ب</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>عدم إعطاء أي معلومة سرية عبر الهاتف أو شبكة الإنترنت ما لم تعرف هوية الشخص أو الطرف المستقبل للمعلومة</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-family:"GE SS Text Light Light",serif;background:white;'>ج</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>عدم مشاركة معلومات الدخول&nbsp;</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>(</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>اسم المستخدم وكلمة المرور</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>)&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>مع الآخرين، وعدم السماح للآخرين باستخدام حساب المستخدم في التطبيق</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>د</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>-&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>استخدام التطبيق من خلال جهاز إلكتروني آمن مع إغلاق التطبيقات المتصلة بالإنترنت غير المستخدمة، والتأكد من أن برنامج الحماية من الفيروسات محدث على الدوام</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>البند السابع</span><span style='font-family:"GE SS Two Medium Medium",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Two Medium Medium",serif;background:white;'>أحكام عامة</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:.0001pt;margin-left:13.1pt;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>اسم الجهة المشرفة على التطبيق</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>شركة تكسب المساندة للتسويق البريد الإلكتروني</span><span style='font-family:"GE SS Text Light Light",serif;background:white;'>:&nbsp;</span><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>تحتفظ إدارة الشركة بحــق إضافــة أو تغييــر أي من أحكام سياسة الخصوصية، وسوف تقــوم إدارة شركة تكسب بإشــعار المستخدم بذلك، ويحــق لإدارة الشركة إنهــاء حساب المستخدم فــي حــال عــدم قبــول المستخدم أي تغييــر فــي سياسة الخصوصية</span><span dir="RTL" style='font-family:"Arial Unicode MS",sans-serif;background:white;'>.</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span dir="RTL" style='font-family:"GE SS Text Light Light",serif;background:white;'>إن اللغة العربية هي المعتمدة في تطبيق الأحكام والشروط، وفي حال نشأ خلاف في تفسير أي نص ورد بأي لغة أخرى فيقدم النص المكتوب باللغة العربية</span></p>
    <p style='margin-top:6.0pt;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;'><span style='font-size:24px;font-family:"Geeza Pro Regular",serif;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;line-height:36.0pt;'><span style='font-size:24px;font-family:"Geeza Pro Regular",serif;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;font-size:16px;font-family:"Helvetica Neue",serif;color:black;border:none;text-align:right;line-height:36.0pt;'><span style='font-size:24px;font-family:"Geeza Pro Regular",serif;background:white;'>&nbsp;</span></p>
    <p style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
</div>